#!/usr/bin/env python3
"""
Unified configure script for the Neural Network Accelerator.

This is the single entry point for all code generation. It reads a YAML
configuration file and generates all necessary VHDL packages, testbenches,
and data files.

Usage:
    python scripts/configure.py [--config configs/xor.nn_conf.yaml]

Generated outputs:
    src/packages/types.vhd          - Fixed-point type definitions
    src/packages/sigmoid_lut_pkg.vhd - Sigmoid lookup table
    testbench/activation_func_tb.vhd - Activation function testbench
    testbench/neuron_tb.vhd          - Neuron testbench
    testbench/layer_tb.vhd           - Layer testbench
"""

import argparse
import sys
from pathlib import Path

# Add scripts directory to path for imports
SCRIPT_DIR = Path(__file__).resolve().parent
ROOT_DIR = SCRIPT_DIR.parent
sys.path.insert(0, str(SCRIPT_DIR))

from config import auto_load_config, AcceleratorConfig


def generate_types_vhd(config: AcceleratorConfig, output_path: Path) -> None:
    """Generate src/packages/types.vhd from configuration."""
    int_bits = config.precision.int_bits
    frac_bits = config.precision.frac_bits
    data_width = config.precision.data_width

    vhdl = f"""\
library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use IEEE.fixed_pkg.all;

package types is

    -- Global Fixed-Point Configuration (generated by configure.py)
    constant DATA_WIDTH : integer := {data_width};
    constant FRAC_BITS : integer := {frac_bits};

    -- Derived constants
    constant INT_BITS : integer := DATA_WIDTH - FRAC_BITS;

    subtype std_logic_bus is std_logic_vector(DATA_WIDTH - 1 downto 0);
    subtype sfixed_bus is sfixed(INT_BITS - 1 downto -FRAC_BITS);
    type std_logic_bus_array is array (integer range<>) of std_logic_vector; -- for neuron weights and inputs
    type weights_matrix is array (integer range<>) of std_logic_bus_array; -- for layer weights
    type layer_config_array is array (natural range <>) of integer;
    type weights_tensor is array (integer range<>) of weights_matrix; -- for network weights

    type real_array is array (integer range<>) of real;
    type boolean_array is array (natural range <>) of boolean;

    function to_sfixed_a(arg: integer) return unresolved_sfixed;
    function to_sfixed_a(arg: real) return unresolved_sfixed;

end package types;

package body types is
    function to_sfixed_a(arg: integer) return unresolved_sfixed is
        variable result : unresolved_sfixed(INT_BITS - 1 downto -FRAC_BITS);
    begin
        result := to_sfixed(
                arg => arg,
                left_index => INT_BITS - 1,
                right_index => -FRAC_BITS);
        return result;
    end function to_sfixed_a;
    function to_sfixed_a(arg: real) return unresolved_sfixed is
        variable result : unresolved_sfixed(INT_BITS - 1 downto -FRAC_BITS);
    begin
        result := to_sfixed(
                arg => arg,
                left_index => INT_BITS - 1,
                right_index => -FRAC_BITS);
        return result;
    end function to_sfixed_a;

end package body types;
"""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(vhdl)
    print(f"  Generated {output_path}")


def generate_sigmoid_lut(config: AcceleratorConfig, root_dir: Path) -> None:
    """Generate sigmoid LUT package by calling existing generator."""
    from gen_sigmoid_pkg import (
        generate_sigmoid_lut as gen_lut,
        generate_vhdl_lut_package,
    )

    lut_values = gen_lut(config.sigmoid, config.precision.frac_bits)
    output_file = root_dir / "src" / "packages" / "sigmoid_lut_pkg.vhd"
    generate_vhdl_lut_package(
        config.sigmoid,
        config.precision.int_bits,
        config.precision.frac_bits,
        lut_values,
        str(output_file),
    )
    print(f"  Generated {output_file}")


def generate_testbenches(config: AcceleratorConfig, root_dir: Path, num_tests: int) -> None:
    """Generate testbenches by calling existing generator."""
    from gen_testbenches import (
        generate_activation_func_tb,
        generate_neuron_tb,
        generate_layer_tb,
    )

    tb_dir = root_dir / "testbench"
    tb_dir.mkdir(parents=True, exist_ok=True)
    int_bits = config.precision.int_bits
    frac_bits = config.precision.frac_bits

    act_path = str(tb_dir / "activation_func_tb.vhd")
    generate_activation_func_tb(config.sigmoid, int_bits, frac_bits, num_tests, act_path)
    print(f"  Generated {act_path}")

    neuron_path = str(tb_dir / "neuron_tb.vhd")
    generate_neuron_tb(config.sigmoid, int_bits, frac_bits, neuron_path)
    print(f"  Generated {neuron_path}")

    layer_path = str(tb_dir / "layer_tb.vhd")
    generate_layer_tb(config.sigmoid, int_bits, frac_bits, layer_path)
    print(f"  Generated {layer_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Configure the Neural Network Accelerator - generate all VHDL from config"
    )
    parser.add_argument(
        "--config",
        type=str,
        default=None,
        help="Path to .nn_conf.yaml config file (auto-detected if not specified)",
    )
    parser.add_argument(
        "--num-tests",
        type=int,
        default=10,
        help="Number of test vectors for testbenches (default: 10)",
    )
    parser.add_argument(
        "--skip-testbenches",
        action="store_true",
        help="Skip testbench generation",
    )
    parser.add_argument(
        "--model",
        type=str,
        default=None,
        help="Path to ONNX model file. Extracts topology and weights.",
    )
    args = parser.parse_args()

    # Load configuration
    print("=" * 60)
    print("Neural Network Accelerator - Configure")
    print("=" * 60)

    config = auto_load_config(str(ROOT_DIR), args.config)

    # If ONNX model provided, parse it and export weights
    parsed_network = None
    if args.model:
        from onnx_parser import (
            parse_onnx, print_network_summary, export_weights_hex,
            DenseLayerInfo, ConvLayerInfo, PoolLayerInfo, FlattenLayerInfo, RNNLayerInfo,
        )

        print(f"\nParsing ONNX model: {args.model}")
        parsed_network = parse_onnx(args.model)
        print_network_summary(parsed_network)

        # Override network config from ONNX model (dense layers only for now)
        from config.loader import NetworkConfig, DenseLayerConfig

        dense_layers = []
        for layer in parsed_network.layers:
            if isinstance(layer, DenseLayerInfo):
                dense_layers.append(
                    DenseLayerConfig(
                        neurons=layer.num_outputs,
                        activation=layer.activation if layer.activation != "none" else "sigmoid",
                    )
                )

        if dense_layers:
            config.network = NetworkConfig(
                name=parsed_network.name,
                layers=dense_layers,
            )

        # Export weights
        print("\n  Exporting weights...")
        data_dir = ROOT_DIR / "data"
        weight_files = export_weights_hex(
            parsed_network,
            data_dir,
            config.precision.int_bits,
            config.precision.frac_bits,
        )
        for name, path in weight_files.items():
            print(f"    {name}: {path}")

    print(f"\nConfiguration: {config.network.name}")
    print(f"  Precision: Q{config.precision.int_bits}.{config.precision.frac_bits} "
          f"({config.precision.data_width}-bit)")
    print(f"  Sigmoid LUT: {config.sigmoid.lut_size} entries, "
          f"range [{-2**config.sigmoid.range_bits}, {2**config.sigmoid.range_bits})")
    print(f"  Network: {' -> '.join(str(l) for l in config.network.layers)}")
    print()

    # Generate types.vhd
    print("[1/3] Generating types package...")
    generate_types_vhd(config, ROOT_DIR / "src" / "packages" / "types.vhd")

    # Generate sigmoid LUT
    print("[2/3] Generating sigmoid LUT package...")
    generate_sigmoid_lut(config, ROOT_DIR)

    # Generate testbenches
    if not args.skip_testbenches:
        print("[3/3] Generating testbenches...")
        generate_testbenches(config, ROOT_DIR, args.num_tests)
    else:
        print("[3/3] Skipping testbench generation")

    print()
    print("=" * 60)
    print("Configuration complete. Run 'make test-all' to verify.")
    print("=" * 60)


if __name__ == "__main__":
    main()
